apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample2-app-blue
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample2-app-blue-green.labels" . | nindent 4 }}
    {{- include "sample2-app-blue-green.blueLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.blueVersion.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "sample2-app-blue-green.blueLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "sample2-app-blue-green.blueLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sample2-app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.blueVersion.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 3000
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: PORT
              value: "3000"
            - name: BUILD_DATE
              value: {{ now | date "2006-01-02T15:04:05Z" | quote }}
            - name: SAMPLE_APP_URL
              value: {{ .Values.externalServices.sampleApp.url | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.blueVersion.resources | nindent 12 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample2-app-green
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample2-app-blue-green.labels" . | nindent 4 }}
    {{- include "sample2-app-blue-green.greenLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.greenVersion.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "sample2-app-blue-green.greenLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "sample2-app-blue-green.greenLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sample2-app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.greenVersion.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 3000
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: PORT
              value: "3000"
            - name: BUILD_DATE
              value: {{ now | date "2006-01-02T15:04:05Z" | quote }}
            - name: SAMPLE_APP_URL
              value: {{ .Values.externalServices.sampleApp.url | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.greenVersion.resources | nindent 12 }}