apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample2-app-blue-green-test
  namespace: argocd
  labels:
    environment: test
    app: sample2-app
    deployment-strategy: blue-green
    argocd.argoproj.io/instance: sample2-app-test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  info:
    - name: Environment
      value: Test
    - name: Application
      value: sample2-app
    - name: Strategy
      value: Blue-Green
  source:
    repoURL: https://gitlab.com/your-org/wb-infrastructure.git
    targetRevision: develop
    path: k8s/apps/sample2-app-blue-green
    helm:
      valueFiles:
        - values.yaml
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - Replace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10