# 서비스 계정 및 역할 정의
# 환경별 권한 분리 및 최소 권한 원칙 적용

# Test 환경 서비스 계정
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-deployer
  namespace: test
  labels:
    environment: test
    team: devops
    app.kubernetes.io/name: test-deployer
    app.kubernetes.io/part-of: rbac-system
  annotations:
    kubernetes.io/description: "Service account for test environment deployments"
automountServiceAccountToken: false

---
# Staging 환경 서비스 계정
apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-deployer
  namespace: staging
  labels:
    environment: staging
    team: devops
    app.kubernetes.io/name: staging-deployer
    app.kubernetes.io/part-of: rbac-system
  annotations:
    kubernetes.io/description: "Service account for staging environment deployments"
automountServiceAccountToken: false

---
# 모니터링 서비스 계정
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-reader
  namespace: monitoring
  labels:
    component: monitoring
    team: devops
    app.kubernetes.io/name: monitoring-reader
    app.kubernetes.io/part-of: monitoring-stack
  annotations:
    kubernetes.io/description: "Service account for monitoring metrics collection"
automountServiceAccountToken: true

---
# ArgoCD 서비스 계정
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: argocd
  labels:
    component: argocd
    team: devops
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd-system
  annotations:
    kubernetes.io/description: "Service account for ArgoCD application controller"
automountServiceAccountToken: true

---
# 개발자 그룹용 서비스 계정
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: test
  labels:
    role: developer
    team: development